# Docker Compose para WhatsApp Clinic Bot
version: '3.8'

services:
  clinic-bot:
    build: .
    container_name: whatsapp-clinic-bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Persistir banco de dados
      - ./data:/app/data
      # Google credentials
      - ./google-credentials.json:/app/google-credentials.json:ro
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Networks (opcional, para conectar com outros serviços)
networks:
  default:
    name: clinic-bot-network

